### ISSUE TITLE
No Swagger2Markup 1.3 CLI counterpart?

### ISSUE THREAD

**Issue by mauricio-morales** [Swagger2Markup/swagger2markup-cli#14]
I'm not running any java project, so running the CLI is VERY convenient but I'm missing the 1.3 release features.

**Comment by RobWin** [comment]
Hi,
I try to publish a new version tomorrow.

Btw if you like Swagger2markup, we would love to get your GitHub Stars.

**Comment by RobWin** [comment]
I've released 1.3.0
If you don't use Java, you could also use the Docker image.
