### ISSUE TITLE
how to generate a markdown file from swagger.json

### ISSUE THREAD

**Issue by everimbaq** [Swagger2Markup/swagger2markup-cli#20]
Hi， i want to generate a MD file from swagger.json while the following cmd generate an adoc file.
`java -jar ./build/libs/swagger2markup-cli-X.X.X.jar convert -i the_swagger_file.json -d /the/path/to/output`

**Comment by RobWin** [comment]
Hi please see http://swagger2markup.github.io/swagger2markup/1.3.1/#_configuration_5
