### ISSUE TITLE
Exception "Tags must not be empty" but there are tags

### ISSUE THREAD

**Issue by sealightPT** [Swagger2Markup/swagger2markup-cli#22]
I'm getting the exception:
`Exception in thread "main" java.lang.NullPointerException: Tags must not be empty, when operations are grouped by tags`

when grouping by tags using this config.prop file:
```
swagger2markup.markupLanguage=ASCIIDOC
swagger2markup.outputLanguage=EN
swagger2markup.pathsGroupedBy=TAGS
swagger2markup.basePathPrefixEnabled=true
```

However, the swagger file (json or yaml) has the tags.
```
---
swagger: '2.0'
info:
  version: v1
  title: Test API
  description: Test API
  termsOfService: None
paths:
  "/api/v{version}/admintasks/integration/catalog":
    get:
      tags:
      - AdminTasks
      summary: Sends the comment.
      operationId: ApiV{versionAdmintasksIntegrationCatalogGet
      consumes: []
      produces: []
      parameters:
      - name: version
        in: path
        required: true
        type: string
      responses:
        '200':
          description: Success
```
  
What am I missing?

**Comment by RobWin** [comment]
The tags in the top level.

**Comment by sealightPT** [comment]
Sorry, could you give an example on where they should be?
This is the output of Swashbuckle for .NetCore converted to yaml

**Comment by RobWin** [comment]
See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#tagObject
