### ISSUE TITLE
Ready to use binaries of the CLI

### ISSUE THREAD

**Issue by kostrse** [Swagger2Markup/swagger2markup-cli#3]
Released binaries of the pre-built app would be great :)

**Comment by RobWin** [comment]
Hi, on my to-do list :)

**Comment by kostrse** [comment]
np :)

**Comment by RobWin** [comment]
Done
its available now. 

https://swagger2markup.readme.io/docs/cli

**Comment by fgabolde** [comment]
This link is currently dead (points to "Project doesn't exist" page).

**Comment by RobWin** [comment]
http://swagger2markup.github.io/swagger2markup/1.1.0/

**Comment by RobWin** [comment]
@fgabolde If you have questions, just join the gitter channel: https://gitter.im/Swagger2Markup/swagger2markup

If you like and use Swagger2Markup, we would love to get your GitHub star.
