### ISSUE TITLE
How to use the -e option?

### ISSUE THREAD

**Issue by dsem** [Swagger2Markup/swagger2markup-cli#4]
for the `-e` option, the help says:

```
-e <examplesPath>
    Include examples into the Paths document
```

What is this `<examplesPath>`?
* Is it the path where the output examples file should go?  The description days it will be included in the Paths document, so it shouldn't need it's own output path.
* Is it the path where the input example file is? Aren't examples supposed to be in-line with responses in the swagger-spec, and thus, not have their own input file?  For example,
```
responses:
  '200':
    description: OK
      schema:
        $ref: '#/definitions/Response'
      examples:
        application/json:
          field1: 23
          field2: 81533
          field3: 83288
          field4: 2440
```

**Comment by RobWin** [comment]
Hi,
its primary to include example HTTP request and response snippets.
I have developed it because I use Springfox and spring-restdocs.
See https://swagger2markup.readme.io/docs/spring-restdocs at the bottom.

**Comment by RobWin** [comment]
You can have a look at the demo project.
https://github.com/Swagger2Markup/spring-swagger2markup-demo
