### ISSUE TITLE
Current version does not compile with latest version of swagger2markup

### ISSUE THREAD

**Issue by nrekretep** [Swagger2Markup/swagger2markup-cli#7]
Hi,

the latest refactorings from swagger2markup have not yet been applied to the Application class. 
Therefore the current version does not compile with the source from the master branch (0.9.3-SNAPSHOT) of swagger2markup.

**Comment by RobWin** [comment]
Yes the next version will be 1.0.0 and not backward compatible. I have to adapt all Plugins and the CLI as soon as it is released.
The Master branch is not up-to-date. The develop branch is used for further enhancements.
