### ISSUE TITLE
Add option to output single file

### ISSUE THREAD

**Issue by mikehwang** [Swagger2Markup/swagger2markup-cli#8]
Currently swagger2markup-cli outputs several documents.  I think it'd be useful for there to be an option for the user to toggle between outputting several documents vs a single document.

**Comment by RobWin** [comment]
Will be supported in v1.0.0

**Comment by mikehwang** [comment]
Does this mean that the PR I created won't be merged in favor of waiting for the release of swagger2markup 1.0.0?

**Comment by RobWin** [comment]
Yes. A snapshot will be available tomorrow.

**Comment by RobWin** [comment]
I hope this is ok for you.

**Comment by mikehwang** [comment]
My thought was that PR https://github.com/Swagger2Markup/swagger2markup-cli/pull/9 would be an intermediary before the release of 1.0.0 as noted in this [comment](https://github.com/Swagger2Markup/swagger2markup-cli/pull/9/commits/50809e2a3805f95902cbc15779202fc47113adbe#diff-a60986013ee9bc1fbdf523834769fb9eR106).  What is the reservation of releasing another patch version before 1.0.0?

In addition, I checked out the `s2m-1.0.0` branch.  I don't see the code for this feature specifically the CLI arg to activate the feature unless the intention is pass it in via the config file.

**Comment by RobWin** [comment]
There is no reservation. I can release a new Version.
But 1.0.0 has many more features and it would be nice if you could test them. I need some Feedback from users :)

**Comment by RobWin** [comment]
Docs can be found here : http://swagger2markup.github.io/swagger2markup/1.0.0-SNAPSHOT/#_command_line_interface

**Comment by RobWin** [comment]
And to store the output in one file, see http://swagger2markup.github.io/swagger2markup/1.0.0-SNAPSHOT/#_conversion_into_a_file_2

**Comment by k0pernikus** [comment]
@RobWin Your provided links are dead. 

I found how to store to a single file out by stumbeling across the flag via `help convert`:

```
        -f <outputFile>, --outputFile <outputFile>
            Output file. Converts the Swagger specification into one file.
```

In my case I had to:

    java -jar ~/bin/swagger2markup-cli-1.1.0.jar  help convert  -i api/swagger/swagger.yaml --outputFile leFile.adoc

**Comment by RobWin** [comment]
The current documentation can be found here: http://swagger2markup.github.io/swagger2markup/1.1.0/

There is also a new Docker image, if you want to use the CLI using Docker.

Btw. If you like and use Swagger2markup, we would love to get your GitHub Stars.
